### ISSUE TITLE
Cannot load package on Azure server

### ISSUE THREAD

**Issue by arilamstein** [BAAQMD/qtytools#2]
I can see the package `qtytools` is listed in the package list on the server. However, when I click the checkbox to load it I get this message:
```
> library(qtytools, lib.loc = "/usr/local/lib/R/site-library")
Error: package ‘tbltools’ required by ‘qtytools’ could not be found
```

When I try to load it "by hand" I get the same error message:
```
> library(qtytools)
Error: package ‘tbltools’ required by ‘qtytools’ could not be found
```

I discovered this because when trying to remove all "no visible global function definition" NOTEs from the tbltools package. One of those is this:
```
  print_tbl: no visible global function definition for ‘total_each’
```

When I type `??total_each` the only hit is the function in `qtytools`. So it appears that at least the package documentation is somehow visible to R. But the package itself is not able to load.

**Comment by dholstius** [comment]
In a clean session on the RStudio server (well, except for the usual things loaded via `.Rprofile` and such), I just ran `library(qtytools)` without incident. Here is my `session_info()`. Were you working in a clean session?

<details>
<pre>
─ Session info ────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Ubuntu 18.04.5 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  C.UTF-8                     
 ctype    C.UTF-8                     
 tz       America/Los_Angeles         
 date     2021-04-12                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date       lib source                           
 ARB           2018.05.17 2021-02-16 [1] Github (BAAQMD/ARB@9844fcc)      
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.3)                   
 backports     1.2.1      2020-12-09 [1] CRAN (R 3.6.3)                   
 broom         0.7.5      2021-02-19 [1] CRAN (R 3.6.3)                   
 cachem        1.0.4      2021-02-13 [1] CRAN (R 3.6.3)                   
 callr         3.5.1      2020-10-13 [1] CRAN (R 3.6.3)                   
 cellranger    1.1.0      2016-07-27 [1] CRAN (R 3.6.3)                   
 cli           2.4.0      2021-04-05 [1] CRAN (R 3.6.3)                   
 codec       * 2021.02.11 2021-02-16 [1] Github (BAAQMD/codec@aff0f4b)    
 colorspace    2.0-0      2020-11-11 [1] CRAN (R 3.6.3)                   
 crayon        1.4.1      2021-02-08 [1] CRAN (R 3.6.3)                   
 curl          4.3        2019-12-02 [1] CRAN (R 3.6.3)                   
 daff        * 0.3.5      2019-05-15 [1] CRAN (R 3.6.3)                   
 data.table  * 1.14.0     2021-02-21 [1] CRAN (R 3.6.3)                   
 DBI           1.1.1      2021-01-15 [1] CRAN (R 3.6.3)                   
 dbplyr        2.1.0      2021-02-03 [1] CRAN (R 3.6.3)                   
 debugme       1.1.0      2017-10-22 [1] CRAN (R 3.6.3)                   
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.3)                   
 devtools    * 2.3.2      2020-09-18 [1] CRAN (R 3.6.3)                   
 diffobj     * 0.3.3      2021-01-07 [1] CRAN (R 3.6.3)                   
 difftools   * 2020.03.17 2021-02-16 [1] Github (BAAQMD/difftools@92f4f48)
 digest      * 0.6.27     2020-10-24 [1] CRAN (R 3.6.3)                   
 downloader  * 0.4        2015-07-09 [1] CRAN (R 3.6.3)                   
 dplyr       * 1.0.5      2021-03-05 [1] CRAN (R 3.6.3)                   
 DT            0.17       2021-01-06 [1] CRAN (R 3.6.3)                   
 ellipsis      0.3.1      2020-05-15 [1] CRAN (R 3.6.3)                   
 ensurer       1.1        2015-04-21 [1] CRAN (R 3.6.3)                   
 fansi         0.4.2      2021-01-15 [1] CRAN (R 3.6.3)                   
 fastmap       1.1.0      2021-01-25 [1] CRAN (R 3.6.3)                   
 fmatch        0.3.2      2021-04-08 [1] Github (BAAQMD/fmatch@1e8aaff)   
 forcats     * 0.5.1      2021-01-27 [1] CRAN (R 3.6.3)                   
 fs            1.5.0      2020-07-31 [1] CRAN (R 3.6.3)                   
 funtools    * 2021.02.12 2021-02-16 [1] Github (BAAQMD/funtools@70cf1df) 
 generics      0.1.0      2020-10-31 [1] CRAN (R 3.6.3)                   
 ggplot2     * 3.3.3      2020-12-30 [1] CRAN (R 3.6.3)                   
 glue        * 1.4.2      2020-08-27 [1] CRAN (R 3.6.3)                   
 gtable        0.3.0      2019-03-25 [1] CRAN (R 3.6.3)                   
 haven         2.3.1      2020-06-01 [1] CRAN (R 3.6.3)                   
 hms           1.0.0      2021-01-13 [1] CRAN (R 3.6.3)                   
 htmltools     0.5.1.1    2021-01-22 [1] CRAN (R 3.6.3)                   
 htmlwidgets   1.5.3      2020-12-10 [1] CRAN (R 3.6.3)                   
 httr          1.4.2      2020-07-20 [1] CRAN (R 3.6.3)                   
 janitor       2.1.0      2021-01-05 [1] CRAN (R 3.6.3)                   
 jsonlite      1.7.2      2020-12-09 [1] CRAN (R 3.6.3)                   
 latex2exp     0.4.0      2015-11-30 [1] CRAN (R 3.6.3)                   
 lazyeval    * 0.2.2      2019-03-15 [1] CRAN (R 3.6.3)                   
 lifecycle     1.0.0      2021-02-15 [1] CRAN (R 3.6.3)                   
 lubridate   * 1.7.10     2021-02-26 [1] CRAN (R 3.6.3)                   
 magrittr      2.0.1      2020-11-17 [1] CRAN (R 3.6.3)                   
 memoise       2.0.0      2021-01-26 [1] CRAN (R 3.6.3)                   
 modelr        0.1.8      2020-05-19 [1] CRAN (R 3.6.3)                   
 munsell       0.5.0      2018-06-12 [1] CRAN (R 3.6.3)                   
 packtools   * 2019.11.05 2021-02-16 [1] Github (BAAQMD/packtools@e14704e)
 pillar        1.5.1      2021-03-05 [1] CRAN (R 3.6.3)                   
 pkgbuild      1.2.0      2020-12-15 [1] CRAN (R 3.6.3)                   
 pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.3)                   
 pkgload       1.2.0      2021-02-23 [1] CRAN (R 3.6.3)                   
 plyr          1.8.6      2020-03-03 [1] CRAN (R 3.6.3)                   
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 3.6.3)                   
 processx      3.4.5      2020-11-30 [1] CRAN (R 3.6.3)                   
 ps            1.6.0      2021-02-28 [1] CRAN (R 3.6.3)                   
 purrr       * 0.3.4      2020-04-17 [1] CRAN (R 3.6.3)                   
 qtytools    * 2021.02.16 2021-02-16 [1] Github (BAAQMD/qtytools@bef0911) 
 R6            2.5.0      2020-10-28 [1] CRAN (R 3.6.3)                   
 Rcpp          1.0.6      2021-01-15 [1] CRAN (R 3.6.3)                   
 readr       * 1.4.0      2020-10-05 [1] CRAN (R 3.6.3)                   
 readxl      * 1.3.1      2019-03-13 [1] CRAN (R 3.6.3)                   
 remotes       2.2.0      2020-07-21 [1] CRAN (R 3.6.3)                   
 reprex        1.0.0      2021-01-27 [1] CRAN (R 3.6.3)                   
 rlang       * 0.4.10     2020-12-30 [1] CRAN (R 3.6.3)                   
 rpivotTable * 0.3.0      2018-01-30 [1] CRAN (R 3.6.3)                   
 rprojroot     2.0.2      2020-11-15 [1] CRAN (R 3.6.3)                   
 rstudioapi    0.13       2020-11-12 [1] CRAN (R 3.6.3)                   
 rvest         1.0.0      2021-03-09 [1] CRAN (R 3.6.3)                   
 scales      * 1.1.1      2020-05-11 [1] CRAN (R 3.6.3)                   
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.3)                   
 snakecase     0.11.0     2019-05-25 [1] CRAN (R 3.6.3)                   
 stringi       1.5.3      2020-09-09 [1] CRAN (R 3.6.3)                   
 stringr     * 1.4.0      2019-02-10 [1] CRAN (R 3.6.3)                   
 strtools    * 2021.02.04 2021-02-16 [1] Github (BAAQMD/strtools@029dc76) 
 tbltools    * 2021.03.24 2021-04-09 [1] local                            
 testthat      3.0.2      2021-02-14 [1] CRAN (R 3.6.3)                   
 tibble      * 3.1.0      2021-02-25 [1] CRAN (R 3.6.3)                   
 tidyr       * 1.1.3      2021-03-03 [1] CRAN (R 3.6.3)                   
 tidyselect  * 1.1.0      2020-05-11 [1] CRAN (R 3.6.3)                   
 tidyverse   * 1.3.0      2019-11-21 [1] CRAN (R 3.6.3)                   
 units         0.6-7      2020-06-13 [1] CRAN (R 3.6.3)                   
 usethis     * 2.0.1      2021-02-10 [1] CRAN (R 3.6.3)                   
 utf8          1.2.1      2021-03-12 [1] CRAN (R 3.6.3)                   
 V8            3.4.0      2020-11-04 [1] CRAN (R 3.6.3)                   
 vartools    * 2020.05.13 2021-02-16 [1] Github (BAAQMD/vartools@97f7926) 
 vctrs         0.3.7      2021-03-29 [1] CRAN (R 3.6.3)                   
 withr         2.4.1      2021-01-26 [1] CRAN (R 3.6.3)                   
 xml2          1.3.2      2020-04-23 [1] CRAN (R 3.6.3)                   

[1] /usr/local/lib/R/site-library
[2] /usr/lib/R/site-library
[3] /usr/lib/R/library
</pre>
</details>

**Comment by arilamstein** [comment]
I am going to close this because I can no longer reproduce it on the server. 

However, I will open another, related issue.

Function [pulll_total](https://github.com/BAAQMD/tbltools/blob/master/R/pull_total.R#L10) uses function `total` from package `qtytools`. But it does not `@importFrom` qtytools, and the DESCRIPTION file does not Import/Suggest/Depend upon `qtytools`. This leads to an error when running R CMD CHECK: `tbltools` needs `qtytools` to run, and so the package should explicitly declare that dependency.

However, when I add `@importFrom qtytools total` and add `qtytools` to the `Import` section of the DESCRIPTION file and run R CMD CHECK I get this error:
```
Warning in (function (dep_name, dep_ver = "*")  :
  Dependency package 'qtytools' not available.
Error: Dependency package(s) 'qtytools' not available.
```

This might be because `qtytools` actually lists `tbltools` in the `Depends` section of the DESCRIPTION file ([link](https://github.com/BAAQMD/qtytools/blob/master/DESCRIPTION#L14)). That is, there seems to be a circular dependency between `qtytools` and `tbltools`. It is not explicity right now. But making it explicit seems to result in an error.

I think that this issue is worth documenting and fixing. However, my inclination is that there is probably a lot of low-hanging fruit that we might want to grab before dealing with this one.
